check args, determine filler and next partition

diff --git a/pmb-add b/pmb-add
--- a/pmb-add
+++ b/pmb-add
@@ -12,3 +12,46 @@ set -o nounset
 #          see the man page for sfdisk for units (e.g. size=10G)
 # * device which holds a fresh unbooted RpiOS (or other) install
 #   (e.g. device=/dev/sdb or device=/dev/mmcblk0)
+# * path to compressed Debian image file
+
+
+usage() {
+    echo device=/dev/sdb size=10G "$0" image=/path/to/compressed/Debian_image \(for example\)
+    exit 1
+}
+
+# verify that needed CMD line args are provided
+if [[ ! -v device ]] || [[ ! -v size ]] || [[ ! -v image ]]
+then
+    usage
+fi
+
+# Check for partition2 (EXT4 partition)
+
+if [ -e "${device}5" ]
+then
+    part5=${device}5
+    partbase=${device}
+elif [ -e "${device}p5" ]
+then
+    part5="${device}p5"
+    partbase=${device}p
+else
+    echo "Can't find partition 5 on $device"
+    echo "be sure to install and run 'pmb-init' before this script."
+    usage
+fi
+
+## Now loop to find the highest numbered partition.
+
+for index in {5..10}
+do    
+  echo $index
+  if [ ! -e ${partbase}$index ]
+  then
+    break
+  fi
+done
+
+filler=$(($index-1))
+echo "next available partition is $index and filler is $filler"
